#!/bin/sh

## Directories ----------------------------
DIR=$(pwd)

## Directories ----------------------------
# Reset
Reset='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

clear

while :
do
    echo
    echo    " [1] Config GUI"
    echo    " [2] Config CLI"

    echo    " [0] or [Ctrl + C] Quit"
    read -p " Enter your choice: " choice
    case $choice in
    0)
        break
        ;;
    1)
        ### X11
        [ ! -f ~/.xprofile ] && ln -sfv $DIR/.config/x/.xprofile $HOME/.xprofile 
        [ ! -f ~/.Xresources ] && ln -sfv $DIR/.config/x/.Xresources $HOME/.Xresources
        ### I3 and i3status 
        ln -sfvr $DIR/.config/i3/ $HOME/.config/
        ln -sfvr $DIR/.config/i3status/ $HOME/.config/
        # ### Awesome 
        # git clone https://github.com/lcpz/lain.git ~/.config/awesome/lain
        # git clone https://github.com/lcpz/awesome-freedesktop.git ~/.config/awesome/freedesktop
        # ln -sfvr $DIR/.config/awesome/ $HOME/.config/
        ### Picom 
        ln -sfvr $DIR/.config/picom/ $HOME/.config/
        ### Alacritty 
        ln -sfvr $DIR/.config/alacritty/ $HOME/.config/
        # .fonts
        [ ! -d $HOME/.fonts ] && mkdir -v $HOME/.fonts
        ln -sfv $DIR/.fonts/feather.ttf $HOME/.fonts/feather.ttf
        ### Rofi 
        ln -sfvr $DIR/.config/rofi/ $HOME/.config/
        ### Dunst 
        ln -sfvr $DIR/.config/dunst/ $HOME/.config/
        # ### Feh 
        # ln -sfvr $DIR/.config/feh/ $HOME/.config/
        ### mpv 
        ln -sfvr $DIR/.config/mpv/ $HOME/.config/
        ### Conky
        ln -sfvr $DIR/.config/conky/ $HOME/.config/
        ### bin 
        ln -sfvr $DIR/.local/bin/ $HOME/.local/
        ;;
    2)
        ### Zsh
        # .cache/zsh
        [ ! -d $HOME/.cache/zsh ] && mkdir -v $HOME/.cache/zsh
        ln -sfvr $DIR/.config/zsh/ $HOME/.config/
        ### Tmux
        ln -sfvr $DIR/.config/tmux/ $HOME/.config/
        ### Lsd
        ln -sfvr $DIR/.config/lsd/ $HOME/.config/
        # Dircolors
        ln -sfv $DIR/.config/dircolors/.dircolors $HOME/.dircolors
        ### Tig
        ln -sfvr $DIR/.config/tig/ $HOME/.config/
        ### Htop
        ln -sfvr $DIR/.config/htop/ $HOME/.config/
        # ### Vim
        # ln -sfvr $DIR/.config/.vim/ $HOME/
        ### Nvim
        ln -sfvr $DIR/.config/nvim/ $HOME/.config/
        ### Ripgrep
        ln -sfvr $DIR/.config/ripgrep/ $HOME/.config/
        ### Fd
        ln -sfvr $DIR/.config/fd/ $HOME/.config/
        ### Neofetch 
        ln -sfvr $DIR/.config/neofetch/ $HOME/.config/
        ### Cava 
        ln -sfvr $DIR/.config/cava/ $HOME/.config/
        ### mpd and ncmpcpp 
        # .cache/mpd
        [ ! -d $HOME/.cache/mpd ] && mkdir -v $HOME/.cache/mpd
        # .cache/mpd/playlists
        [ ! -d $HOME/.cache/mpd/playlists ] && mkdir -v $HOME/.cache/mpd/playlists
        # .config/mpd
        ln -sfvr $DIR/.config/mpd/ $HOME/.config/
        # .config/ncmpcpp
        ln -sfvr $DIR/.config/ncmpcpp/ $HOME/.config/
        ;;
    *)
        echo "Sorry, choice understand"
        ;;
    esac
done
