#!/bin/sh

## Directories ----------------------------
DIR=$(pwd)

## Directories ----------------------------
# Reset
Reset='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

clear

while :
do
    echo
    echo -e  "${Green} [1] Config GUI   ${Reset}"
    echo -e  "${Blue} [2] Config CLI    ${Reset}"
    echo -e  "${Yellow} [0] Quit        ${Reset}"
    echo
    read -p " Enter your choice: " choice
    case $choice in
    0)
        break
        ;;
    1)
        ### X11
        [ ! -f ~/.xprofile ] && ln -sfv $DIR/.config/x/.xprofile $HOME/.xprofile 
        [ ! -f ~/.Xresources ] && ln -sfv $DIR/.config/x/.Xresources $HOME/.Xresources
        ### I3 and i3status 
        ln -sfvr $DIR/.config/i3/ $HOME/.config/
        ln -sfvr $DIR/.config/i3status/ $HOME/.config/
        ### Awesomewm 
        ln -sfvr $DIR/.config/awesome/ $HOME/.config/
        ### Picom 
        ln -sfvr $DIR/.config/picom/ $HOME/.config/
        ### Alacritty 
        ln -sfvr $DIR/.config/alacritty/ $HOME/.config/
        ### Rofi 
        # .local/share/fonts 
        [ ! -d $HOME/.local/share/fonts ] && mkdir -p $HOME/.local/share/fonts
        ln -sfv $DIR/.local/share/fonts/feather.ttf $HOME/.local/share/fonts/feather.ttf
        # .config/rofi
        ln -sfvr $DIR/.config/rofi/ $HOME/.config/
        ### Dunst 
        ln -sfvr $DIR/.config/dunst/ $HOME/.config/
        ### mpv 
        ln -sfvr $DIR/.config/mpv/ $HOME/.config/
        ### Zathura
        ln -sfvr $DIR/.config/zathura/ $HOME/.config/
        ;;
    2)
        ### bin 
        ln -sfvr $DIR/.local/bin/ $HOME/.local/
        ### Zsh
        ln -sfvr $DIR/.config/zsh/ $HOME/.config/
        ### Tmux
        ln -sfvr $DIR/.config/tmux/ $HOME/.config/
        ### Lsd
        ln -sfvr $DIR/.config/lsd/ $HOME/.config/
        ### Dircolors
        ln -sfv $DIR/.config/dircolors/.dircolors $HOME/.dircolors
        ### Tig
        ln -sfvr $DIR/.config/tig/ $HOME/.config/
        ### Htop
        ln -sfvr $DIR/.config/htop/ $HOME/.config/
        ### Nvim
        ln -sfvr $DIR/.config/nvim/ $HOME/.config/
        ### Ranger
        ln -sfvr $DIR/.config/ranger/ $HOME/.config/
        ### Ripgrep
        ln -sfvr $DIR/.config/ripgrep/ $HOME/.config/
        ### Fd
        ln -sfvr $DIR/.config/fd/ $HOME/.config/
        ### Neofetch 
        ln -sfvr $DIR/.config/neofetch/ $HOME/.config/
        ### Cava 
        ln -sfvr $DIR/.config/cava/ $HOME/.config/
        ;;
    *)
        echo "Sorry, choice understand"
        ;;
    esac
done
