#!/bin/bash

Reset='\033[0m'

Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
Yellow='\033[0;33m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
White='\033[0;37m'

BrightBlack='\033[1;30m'
BrightRed='\033[1;31m'
BrightGreen='\033[1;32m'
BrightYellow='\033[1;33m'
BrightBlue='\033[1;34m'
BrightPurple='\033[1;35m'
BrightCyan='\033[1;36m'
BrightWhite='\033[1;37m'

DIR=$(pwd)

clear

while :; do
    echo
    echo -e "${Blue} [1] Setup ${Reset}"
    echo -e "${Yellow} [0] Quit ${Reset}"
    echo

    read -p " Enter your choice: " choice

    case $choice in
    0)
        break
        ;;
    1)
        # Get superuser permission
        sudo echo

        # GUI
        [ ! -f ~/.xprofile ] && ln -sfv $DIR/.config/.xprofile $HOME/.xprofile
        [ ! -f ~/.Xresources ] && ln -sfv $DIR/.config/.Xresources $HOME/.Xresources
        ln -sfv $DIR/.config/mimeapps.list $HOME/.config/mimeapps.list
        ln -sfvr $DIR/.config/awesome/ $HOME/.config/
        ln -sfvr $DIR/.config/picom/ $HOME/.config/
        ln -sfvr $DIR/.config/alacritty/ $HOME/.config/
        ln -sfvr $DIR/.config/rofi/ $HOME/.config/
        ln -sfvr $DIR/.config/mpv/ $HOME/.config/
        ln -sfvr $DIR/.config/zathura/ $HOME/.config/

        # CLI
        ln -sfvr $DIR/.local/bin/ $HOME/.local/
        ln -sfvr $DIR/.config/zsh/ $HOME/.config/
        ln -sfvr $DIR/.config/tmux/ $HOME/.config/
        ln -sfvr $DIR/.config/lsd/ $HOME/.config/
        ln -sfv $DIR/.config/.dircolors $HOME/.dircolors
        ln -sfvr $DIR/.config/tig/ $HOME/.config/
        ln -sfvr $DIR/.config/htop/ $HOME/.config/
        ln -sfvr $DIR/.config/nvim/ $HOME/.config/
        ln -sfvr $DIR/.config/ranger/ $HOME/.config/
        ln -sfvr $DIR/.config/ripgrep/ $HOME/.config/
        ln -sfvr $DIR/.config/fd/ $HOME/.config/
        ln -sfvr $DIR/.config/neofetch/ $HOME/.config/
        ln -sfvr $DIR/.config/cava/ $HOME/.config/
        ln -sfvr $DIR/.config/btop/ $HOME/.config/

        # MISC
        sudo sed -i -e 's/#Color/Color/g' /etc/pacman.conf &&
            echo "[pacman] Automatically enable colors only when pacman’s output is on a tty."
        sudo sed -i -e 's/#VerbosePkgLists/VerbosePkgLists/g' /etc/pacman.conf &&
            echo "[pacman] Displays name, version and size of target packages formatted as a table for upgrade, sync and remove operations."
        [ -f /usr/bin/xdg-user-dirs-update ] && xdg-user-dirs-update &&
            echo "[xdg-user-dirs] Update XDG user dir configuration."
        ;;
    *)
        echo
        echo "Sorry, choice understand"
        ;;
    esac
done
