require("dat.options")
require("dat.keymaps")
require("dat.plugins")
-- require("dat.autocommands")
require("dat.colorscheme")
require("dat.lualine")
require("dat.bufferline")
require("dat.nvimtree")
require("dat.telescope")
require("dat.treesitter")
require("dat.gitsigns")
require("dat.colorizer")
require("dat.illuminate")
require("dat.autopairs")
require("dat.comment")
require("dat.lsp")
require("dat.cmp")

-- require("dat.startscreen")
