# ===================================================================
# == Options
# ===================================================================

# Show hidden files? You can toggle this by typing 'zh'
set show_hidden true

# Use one of the supported image preview protocols
set preview_images true

# Draw borders around columns? (separators, outline, both, or none)
# Separators are vertical lines between columns.
# Outline draws a box around all the columns.
# Both combines the two.
set draw_borders both

# ===================================================================
# == Define keys for the browser
# ===================================================================

# Filesystem Operations
map DD shell gio trash %s
