# LightDM GTK Configuration
[greeter]
# Appearance:
theme-name = Orchis-Dark-Compact
icon-theme-name = Papirus-Dark
cursor-theme-name = Vimix-white-cursors
background = #2c2c2c
# Fonts:
font-name = RobotoMono Nerd Font 14
xft-dpi = 120
# Login window:
hide-user-image = true
# Panel:
indicators = ~spacer;~session;~a11y;~power;~spacer
