-- Core
require("core.options")
require("core.keymaps")
require("core.plugins")
require("core.autocommands")
-- require("core.startscreen")
-- Plugin
require("plugins.colorscheme")
require("plugins.whichkey")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.nvimtree")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.colorizer")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.cmp")
require("plugins.illuminate")
require("plugins.dressing")
require("plugins.breadcrumbs")
require("plugins.scrollbar")
require("plugins.spectre")
-- LSP
require("lsp")
